tag_specification:
  name: '4.3'
  namespace: ocp
promotion:
  namespace: openshift
  name: knative-nightly
base_images:
  base:
    name: '4.3'
    namespace: ocp
    tag: base
build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
canonical_go_repository: knative.dev/serving
tests:
- as: e2e-aws-ocp-43
  commands: "make test-e2e"
  openshift_installer_src:
    cluster_profile: aws
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
images:
- dockerfile_path: openshift/ci-operator/knative-images/webhook/Dockerfile
  from: base
  to: knative-serving-webhook
- dockerfile_path: openshift/ci-operator/knative-images/activator/Dockerfile
  from: base
  to: knative-serving-activator
- dockerfile_path: openshift/ci-operator/knative-images/nscert/Dockerfile
  from: base
  to: knative-serving-nscert
- dockerfile_path: openshift/ci-operator/knative-images/istio/Dockerfile
  from: base
  to: knative-serving-istio
- dockerfile_path: openshift/ci-operator/knative-images/controller/Dockerfile
  from: base
  to: knative-serving-controller
- dockerfile_path: openshift/ci-operator/knative-images/autoscaler-hpa/Dockerfile
  from: base
  to: knative-serving-autoscaler-hpa
- dockerfile_path: openshift/ci-operator/knative-images/certmanager/Dockerfile
  from: base
  to: knative-serving-certmanager
- dockerfile_path: openshift/ci-operator/knative-images/queue/Dockerfile
  from: base
  to: knative-serving-queue
- dockerfile_path: openshift/ci-operator/knative-images/autoscaler/Dockerfile
  from: base
  to: knative-serving-autoscaler
- dockerfile_path: openshift/ci-operator/knative-test-images/pizzaplanetv2/Dockerfile
  from: base
  to: knative-serving-test-pizzaplanetv2
- dockerfile_path: openshift/ci-operator/knative-test-images/helloworld/Dockerfile
  from: base
  to: knative-serving-test-helloworld
- dockerfile_path: openshift/ci-operator/knative-test-images/runtime/Dockerfile
  from: base
  to: knative-serving-test-runtime
- dockerfile_path: openshift/ci-operator/knative-test-images/timeout/Dockerfile
  from: base
  to: knative-serving-test-timeout
- dockerfile_path: openshift/ci-operator/knative-test-images/observed-concurrency/Dockerfile
  from: base
  to: knative-serving-test-observed-concurrency
- dockerfile_path: openshift/ci-operator/knative-test-images/grpc-ping/Dockerfile
  from: base
  to: knative-serving-test-grpc-ping
- dockerfile_path: openshift/ci-operator/knative-test-images/failing/Dockerfile
  from: base
  to: knative-serving-test-failing
- dockerfile_path: openshift/ci-operator/knative-test-images/autoscale/Dockerfile
  from: base
  to: knative-serving-test-autoscale
- dockerfile_path: openshift/ci-operator/knative-test-images/pizzaplanetv1/Dockerfile
  from: base
  to: knative-serving-test-pizzaplanetv1
- dockerfile_path: openshift/ci-operator/knative-test-images/wsserver/Dockerfile
  from: base
  to: knative-serving-test-wsserver
- dockerfile_path: openshift/ci-operator/knative-test-images/httpproxy/Dockerfile
  from: base
  to: knative-serving-test-httpproxy
- dockerfile_path: openshift/ci-operator/knative-test-images/singlethreaded/Dockerfile
  from: base
  to: knative-serving-test-singlethreaded
- dockerfile_path: openshift/ci-operator/knative-test-images/hellovolume/Dockerfile
  from: base
  to: knative-serving-test-hellovolume
